server:
  host: 0.0.0.0
  port: 3000
swagger:
  title: Documentaton API NestJs
  description: Documentation de l'API du projet de technologies du web
  version: 1.0
  tag: api
  path: documentation
mongodb:
  uri: mongodb://0.0.0.0:27017/projetDB
  options:
    useNewUrlParser: true
    useUnifiedTopology: true
    useFindAndModify: false
